habit:
  images:
    common:
      registry: 'ghcr.io'
      folder: 'wttech/habit'
      tag: '${version}'
    request-persister:
      image: 'request-persister'
    request-graph-server:
      image: 'request-graph-server'
    mock-server:
      image: 'mock-server'
    environment-front-proxy:
      image: 'environment-front-proxy'
