name: Test

on:
  [push, workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Verify build
        run: ./gradlew --stacktrace build test javadoc publishToLocalDocker
